### ISSUE TITLE
Linkifying breaks descriptions when editing a project

### ISSUE THREAD

**Issue by usmonster** [chomb94/foundry#26]
If a project description includes a URL, this will be broken when attempting to later edit the description.

I believe this is because the linkify plugin introduced by @ninsuo in #25 is mistakenly/badly parsing & transforming the contenteditable container that ckeditor uses for WYSIWYG editing.

I can maybe make a PR in a week or so, but feel free to fix it before then. ;)

**Comment by chomb94** [comment]
Thanks Usmonster :) !
